// Downloads the Wikipedia singles draw for every tournament in src/data.js that names one (field `w`),
// parses the bracket templates into matches, and writes src/draws.js.
// Run: node scripts/fetch-draws.mjs && node build.mjs
import fs from 'fs';

const UA = {'User-Agent': 'CourtAtlas/1.0 (https://github.com/winterai-newchapter/court-atlas)'};
const API = 'https://en.wikipedia.org/w/api.php';
const { T, PLAYERS } = new Function(fs.readFileSync('src/data.js', 'utf8') + ';return {T, PLAYERS};')();

// The parser is shared with the browser's live refresh (src/live.js)
const { slug, parseDraw, toDraw, wiki } = new Function(fs.readFileSync('src/parse.js', 'utf8') + ';return WIKIDRAW;')();
export { slug };

async function fetchPages(titles){
  const out = {};
  for (let i = 0; i < titles.length; i += 10){
    const batch = titles.slice(i, i + 10);
    const q = new URLSearchParams({action:'query', prop:'revisions', rvprop:'ids|timestamp|content', rvslots:'main',
      titles: batch.join('|'), redirects:'1', format:'json', formatversion:'2'});
    const r = await (await fetch(`${API}?${q}`, {headers: UA})).json();
    const alias = {};
    for (const n of r.query.normalized || []) alias[n.to] = n.from;
    for (const n of r.query.redirects || []) alias[n.to] = alias[n.from] || n.from;
    for (const p of r.query.pages){
      const asked = alias[p.title] || p.title;
      if (p.missing){ out[asked] = null; continue; }
      const rev = p.revisions[0];
      out[asked] = {title: p.title, rev: rev.revid, at: rev.timestamp, text: rev.slots.main.content};
    }
  }
  return out;
}

const jobs = [];
for (const t of T) for (const [tour, title] of Object.entries(t.w || {})) jobs.push({t, tour, title});
const pages = await fetchPages([...new Set(jobs.map(j => j.title))]);
const fetched = new Date().toISOString().replace(/\.\d+Z$/, 'Z');

const SRC = {}, DRAWS = {}, PEOPLE = {};
for (const {t, tour, title} of jobs){
  const pg = pages[title], key = `${t.id}/${tour}`;
  if (!pg){ console.warn(`missing page: ${title}`); continue; }
  SRC[key] = {u: wiki(pg.title), rev: pg.rev, at: pg.at};
  if (tour === 'Team') continue;
  const parsed = parseDraw(pg.text), {matches} = parsed;
  if (!matches.length){ console.warn(`no draw yet: ${title}`); }
  DRAWS[key] = toDraw(parsed, PEOPLE);
  // Cross-check the final against the hand-entered result in data.js
  const fin = matches.find(m => m.round.toLowerCase() === 'final' && m.w >= 0);
  const r = t.res.find(x => x.t === tour);
  if (fin && r){
    const w = fin.w === 0 ? fin.a : fin.b;
    if (slug(w) !== slug(r.w)) console.warn(`final mismatch ${key}: data.js says ${r.w}, Wikipedia says ${w}`);
  }
  if (!fin && r) console.warn(`no final in draw for ${key}`);
}
for (const tour of ['ATP','WTA']) for (const p of PLAYERS[tour]) if (!PEOPLE[slug(p.n)]) console.warn(`top-10 player not in any draw: ${p.n}`);

const out = `/* Generated by scripts/fetch-draws.mjs on ${fetched} from Wikipedia. Do not edit by hand. */
const FETCHED = '${fetched}';
const TODAY = new Date(FETCHED);
/* key "<tournament id>/<tour>": u page URL, rev revision id, at revision time */
const SRC = ${JSON.stringify(SRC)};
/* slug: [name, IOC flag code, Wikipedia article if it differs from name] */
const PEOPLE = ${JSON.stringify(PEOPLE)};
/* rounds: labels; e: slug -> seed/entry tag; m: [round index, player A, player B, winner (0 A, 1 B, -1 not played), score] */
const DRAWS = ${JSON.stringify(DRAWS)};
`;
fs.writeFileSync('src/draws.js', out);
const n = Object.values(DRAWS).reduce((a, x) => a + x.m.length, 0);
console.log(`wrote src/draws.js: ${Object.keys(DRAWS).length} draws, ${n} matches, ${Object.keys(PEOPLE).length} players, ${(out.length/1024).toFixed(0)} KB`);
